const helper = require('./testfunc');

test('Ensures a 4 digit number is generated by generateDigits', () => {
    expect(helper.generateDigits(4)).toMatch(new RegExp('[0-9]{4}'));
});

test('Ensures no negative values are chosen', () => {
    expect(parseInt(helper.generateDigits(4))).toBeGreaterThanOrEqual(0);
});

test('Ensures no output above 5 digits', () => {
    expect(parseInt(helper.generateDigits(4))).toBeLessThanOrEqual(9999);
});

test('Ensures values are being correctly encoded', () => {
    expect(helper.encodeOutput('&<">')).toBe('&amp&lt&quot&gt');
});

test('Ensures values are being correctly decoded', () => {
    expect(helper.decodeOutput("&lt&gt&amp&#x27")).toBe("<>&'");
});